### ISSUE TITLE
Subclass-of relation of https://w3id.org/pmd/tto/ProofStrength

### ISSUE THREAD

**Issue by MattTJung** [materialdigital/application-ontologies#37]
Hi,

https://w3id.org/pmd/tto/ProofStrength is currently a subclass of https://w3id.org/pmd/tto/Extension. I think that is a mistake.

BR
Matthias

**Comment by MarkusSchilling** [comment]
Indeed, this was a mistake - possibly a misclick...
Thank you for reporting the error! 

This was fixed in [PR #41](https://github.com/materialdigital/application-ontologies/pull/41) and the respective [commit](https://github.com/materialdigital/application-ontologies/commit/b559db62a3569b3cd7caf31dbb76625153a4c0e3).
